import = [
"~/.config/alacritty/fonts.toml",
"~/.config/alacritty/themes/darkly.toml",
]

live_config_reload = true

[window]
opacity = 0.8
decorations = "Full"
startup_mode = "Windowed"
padding = {x = 0, y = 0}
position = {x = 12, y = 12}
dimensions = {columns = 116, lines = 36}

[scrolling]
history = 10000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
blink_timeout = 0
blink_interval = 600
unfocused_hollow = false
style = {shape = "Block", blinking = "Always"}

[mouse]
hide_when_typing = true
