[font]
normal = {family = "Fragment Mono", style = "Regular"}
bold = {family = "Fragment Mono", style = "Bold"}
italic = {family = "Fragment Mono", style = "Italic"}

size = 10
offset = {x = 0, y = 0}
glyph_offset = {x = 0, y = 0}

[colors]
draw_bold_text_with_bright_colors = true
